/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "roomman.h"
#include <stdio.h>
#include <stdint.h>
#include "../libsrc/include/roomman.h"
CLIENT * clnt = NULL;


void 
roomman_rpc_init(char *hostname) {
    clnt = clnt_create(hostname, ROOMMAN_PROG, ROOMMAN_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(hostname);
        exit(1);
    }
}
roomid_t roomman_create_room(char *building_name, char *room_name, uint16_t max_pers){
	printf("roomman create room \n");
	struct room  roomman_create_roomx_1_arg;
	char *building = strdup(building_name);
	char *room = strdup(room_name);
	roomman_create_roomx_1_arg.building_name = building;
	roomman_create_roomx_1_arg.room_name = room;
	roomman_create_roomx_1_arg.max_pers = max_pers;
	roomid_t  *result_2;
	result_2 = roomman_create_roomx_1(&roomman_create_roomx_1_arg, clnt);
	printf("test------\n");

	if (result_2 == (roomid_t *) NULL) {
				clnt_perror (clnt, "call failed");
				exit(2);
			} else
			{	if (*result_2 == ROOMMAN_ERR_DUPLICATE_ROOM)
				{
					printf("Duplicate room !!\n");
				
				}
				else if (*result_2 == ROOMMAN_ERR_INVALID_ROOM)
				{
					printf("Invalid room !!\n");
				} else
				{
					printf("Create room success ID  %d\n ", *result_2);
					printf("Done !!\n");
				}
			}
	return *result_2;

}

int16_t 	roomman_delete_room(roomid_t rid){
	roomid_t  roomman_delete_roomx_1_arg;
	int16_t  *result_3;

	roomman_delete_roomx_1_arg = rid;
	result_3 = roomman_delete_roomx_1(&roomman_delete_roomx_1_arg, clnt);

	if (result_3 == (int16_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_3;
				
}

int16_t 	roomman_update_capacity(roomid_t rid, uint16_t new_capacity){
		int16_t  *result_4;
		struct kappa  roomman_update_capacityx_1_arg;
		roomman_update_capacityx_1_arg.rid = rid;
		roomman_update_capacityx_1_arg.max_pers = new_capacity;
		result_4 = roomman_update_capacityx_1(&roomman_update_capacityx_1_arg, clnt);
		if (result_4 == (int16_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_4;
}

int16_t  roomman_reserve_room(roomid_t rid){
	int16_t  *result_5;
	roomid_t  roomman_reserve_roomx_1_arg;
	roomman_reserve_roomx_1_arg = rid;
	result_5 = roomman_reserve_roomx_1(&roomman_reserve_roomx_1_arg, clnt);
	if (result_5 == (int16_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return *result_5;
}

int16_t roomman_clear_reservation (roomid_t rid){
	int16_t  *result_6;
	roomid_t  roomman_clear_reservationx_1_arg;
	roomman_clear_reservationx_1_arg = rid;
	result_6 = roomman_clear_reservationx_1(&roomman_clear_reservationx_1_arg, clnt);
	if (result_6 == (int16_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_6;

}

int16_t roomman_readentry(roomid_t ID, char *building, char *name, uint16_t *capacity){
	struct room_entry  *result_7;
	roomid_t  roomman_readentryx_1_arg;
	roomman_readentryx_1_arg = ID;
					
	result_7 = roomman_readentryx_1(&roomman_readentryx_1_arg, clnt);
	if (result_7 == (struct room_entry *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	building = result_7->building_name;
	name = result_7->room_name;
	capacity = result_7->max_pers;
	int16_t reserve = result_7->reserve;
	
	return reserve;
}

roomid_t roomman_lookup(const char *building, const char *room_name){
	roomid_t  *result_8;
	struct room_lookup  roomman_lookupx_1_arg;
	char *building_name = strdup(building);
	char *room = strdup(room_name);
	roomman_lookupx_1_arg.building_name = building_name;
	roomman_lookupx_1_arg.room_name = room;
	result_8 = roomman_lookupx_1(&roomman_lookupx_1_arg, clnt);

	return *result_8;
}

roomid_t roomman_directory (int32_t *fdptr, const char *building, const char *room_name){
	roomid_t  *result_9;
	struct room_direct  roomman_directoryx_1_arg;
	roomman_directoryx_1_arg.fdptr = fdptr;
	char *building_name = strdup(building) ;
	char *room = strdup(room_name);
	roomman_directoryx_1_arg.building_name = building_name;
	roomman_directoryx_1_arg.room_name = room;
	result_9 = roomman_directoryx_1(&roomman_directoryx_1_arg, clnt);
	if (result_9 == (roomid_t *) NULL) {
		clnt_perror (clnt, "call failed directory");
	}
	return *result_9;
}

void roomman_rpc_terminate(void){
	clnt_destroy (clnt);
}
