/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "roomman.h"
#include "../libsrc/include/roomman.h"


int16_t *
roomman_initx_1_svc(bool_t *argp, struct svc_req *rqstp)
{
	static int16_t  result;
	printf("Init Room function called\n");

	uint16_t set = *argp;
	result = roomman_init(set);
	return &result;
}

roomid_t *
roomman_create_roomx_1_svc(struct room *argp, struct svc_req *rqstp)
{
	static roomid_t  result;

	printf("Create Room function called\n");
	char *building_name = strdup(argp->building_name);
    char *room_name = strdup(argp->room_name);
    int16_t max_pers = argp->max_pers;

	printf("parameters: %s, %s, %d \n", building_name, room_name,max_pers);
	
	result = roomman_create_room(building_name,room_name, max_pers);
	if (result == ROOMMAN_ERR_DUPLICATE_ROOM)
	{
		printf("Duplicate room !!\n");
	
	}
	else if (result == ROOMMAN_ERR_INVALID_ROOM)
	{
		printf("Invalid room !!\n");
	} else
	{
		printf("Result %d \n ", result);
		printf("Done !!\n");
	}
	
	return &result;
}

int16_t *
roomman_delete_roomx_1_svc(roomid_t *argp, struct svc_req *rqstp)
{
	static int16_t  result;

	roomid_t room_id = *argp;
	printf("Delete Room function called\n");
	result = roomman_delete_room(room_id);
	if (result == 0)
	{
		printf("Room ID %d  is deleted\n", room_id);
	}
	else
	{
		printf("Room ID %d  is not deleted\n", room_id);
	}
	return &result;
}

int16_t *
roomman_update_capacityx_1_svc(struct kappa *argp, struct svc_req *rqstp)
{
	static int16_t  result;
	
	printf("Update Room function called\n");
	roomid_t rid = argp->rid;
    int16_t max_pers = argp->max_pers;
	result = roomman_update_capacity(rid,max_pers);

	if (result == 0)
	{
		printf("Update room %d succesfull with %d \n", rid, max_pers);
	} else
	{
		printf("Update room %d not succesfull with %d \n", rid, max_pers);
	} 
	
	return &result;
}

int16_t *
roomman_reserve_roomx_1_svc(roomid_t *argp, struct svc_req *rqstp)
{
	static int16_t  result;
	printf("Reserve Room function called\n");
	roomid_t rid = *argp;
	result = roomman_reserve_room(rid);
	if (result == 0)
	{
		printf("Reserve room %d succesfull\n", rid);
	}
	else
	{
		printf("Reserve room %d unsuccesfull\n", rid);
	}
	

	return &result;
}

int16_t *
roomman_clear_reservationx_1_svc(roomid_t *argp, struct svc_req *rqstp)
{
	static int16_t  result;
	printf("Clear reservation Room function called\n");
	roomid_t rid = *argp;
	result = roomman_clear_reservation(rid);
	if (result == 0)
	{
		printf("Clear reservation room %d succesfull\n", rid);
	}
	else
	{
		printf("Clear reservation room %d unsuccesfull\n", rid);
	}
	
	return &result;
}

struct room_entry *
roomman_readentryx_1_svc(roomid_t *argp, struct svc_req *rqstp)
{
	static struct room_entry  result;
	printf("Readentry Room function called\n");
	roomid_t rid = *argp;

    char building[ROOMMAN_MAX_NAME];
	char room_name[ROOMMAN_MAX_NAME];
	uint16_t capacity[10];
	int16_t reserve;
	reserve = roomman_readentry(rid, building, room_name, capacity);
	result.rid = rid;
	result.reserve = reserve;
	result.max_pers = capacity;
	result.building_name = strdup(building);
	result.room_name = strdup(room_name);
	
	return &result;
}

roomid_t *
roomman_lookupx_1_svc(struct room_lookup *argp, struct svc_req *rqstp)
{
	static roomid_t  result;

	printf("Look up Room function called\n");
	char *building_name = strdup(argp->building_name);
    char *room_name = strdup(argp->room_name);

	printf("parameters: %s, %s \n", building_name, room_name);
	result = roomman_lookup(building_name, room_name);
	if (result >= 0)
	{
		printf("Room found %d \n", result);
	}
	else
	{
		printf("In function roomman_lookup(): Error: Room not found");
	}
	
	
	return &result;
}

roomid_t *
roomman_directoryx_1_svc(struct room_direct *argp, struct svc_req *rqstp)
{
	static roomid_t  result;
	printf("Directory Room function called\n");
	int32_t *initial = argp->fdptr;
	
	result = roomman_directory(initial,NULL ,NULL );
	if (result >= 0)
	{
		printf("Room found %d \n", result);
	}
	else
	{
		printf("In function roomman_directory(): Error: Room not found");
	}
	return &result;
}
